### ISSUE TITLE
remove error in open sock problem code

### ISSUE THREAD

**Issue by utkarsh357** [utkarsh357/correction#1]

**Comment by utkarsh147-del** [comment]
assign this to me

**Comment by utkarsh357** [comment]
do it

**Comment by utkarsh147-del** [comment]
#include <bits/stdc++.h> 
vector<int> findSpans(vector<int> &price) {
    // Write your code here.
    
    stack<int>s;
    vector<int>arr;
    s.push(-1);
    for(int i=0;i<price.size();i++)
    {
       // cout<<"top "<<s.top()<<endl;
    //    cout<<"i "<<i<<endl;
        if(s.top()==-1)
            arr.push_back(1);
        else if(price[s.top()]>price[i])
        {
          //  cout<<"b"<<endl;
            arr.push_back(i-s.top());
        }
        else if(price[s.top()]<=price[i])
        {
        //    cout<<"c"<<endl;
            while(s.top()!=-1&&price[s.top()]<=price[i])
            {
                s.pop();
            }
         //    cout<<"top "<<s.top()<<endl;
            if(s.top()==-1)
            {
               // cout<<"i "<<i<<endl;
                arr.push_back(i+1);
            }
            else
                arr.push_back(i-s.top());
                
        }
        
      //  cout<<"ar "<<arr[arr.size()-1]<<endl;
        s.push(i);
    }
    
    return arr;
    
}
